#!/bin/tcsh

setenv SYN_AREA /home/cdsl14/test_innovus/syn_pnr_pt_flow/syn
setenv RTL_DIR /home/cdsl14/test_innovus/syn_pnr_pt_flow/rtl 
setenv PNR_AREA /home/cdsl14/test_innovus/syn_pnr_pt_flow/pnr
setenv PT_AREA /home/cdsl14/test_innovus/syn_pnr_pt_flow/pt
setenv PDK_DIR /home/cdsl14/test_innovus/syn_pnr_pt_flow/asap7nm_pdk
setenv DESIGN_DIR /home/cdsl14/test_innovus/syn_pnr_pt_flow/design_files
setenv USER_DIR $PNR_AREA/user_files

setenv DESIGN des
setenv PDK asap7nm
